### ISSUE TITLE
Lady Nina - resonance has no effect with self oscillation on

### ISSUE THREAD

**Issue by glocke01** [kockie69/RPJ#67] opened 2022-08-31 17:43 UTC
If self oscillation is on and gain compensation is off, the resonance dial has no audible effect. With gain compensation off, turning up the resonance dial seems only to reduce gain.

**Comment by kockie69** [comment] 2022-10-17 19:56
On what platform are you working (Windows, linux or Mac). I have checked on Windows and it definitely get into self oscilation. And is this happening on all the outputs (LPF,HPF,BPF,BSF)?

The reduction of gain when increasing the resonance is by design. For every dB increase in peak gain due to the increased Q, the filter response is lowered by half that value in dB.

**Comment by kockie69** [comment] 2022-10-18 19:25
If self oscillation is on and gain compensation is off, the resonance dial has no audible effect.  This is also by design. Self oscilation for this filter is achieved when Q is infinite, so that is what is set in the code of the filter. Changing Q has no effect (Q will be infinite, whatever Q you set)

**Closed as completed by kockie69** 2022-10-18 19:25 UTC
Labels: wontfix
